import {
  product1,
  product2,
  product3,
  product4,
  product5,
  product6,
  product7,
  product8,
  product9,
  product10,
  product11,
  product12,
  product13,
  product14,
  product15,
  product16,
  product17,
  product18,
  product19,
  product20,
  product21,
  product22,
  product23,
  product24,
  product25,
  product26,
  product27,
  product28,
  product29,
  product30,
  product31,
  product32,
  product33,
  product34,
  product35,
  product36,
  product37,
  product38,
  product39,
  product40,
  product41,
  product42,
  product43,
  product44,
  product45,
  product46,
  product47,
  product48,
  product49,
  product50,
  product51,
  product52,
  product53,
  product54,
  product55,
  product56,
  product57,
  product58,
  product59,
  product60,
  product61,
  product62,
  product63,
  product64,
  product65,
  product66,
  product67,
  product68,
  product69,
  product70,
  product71,
  product72,
  product73,
  product74,
  product75,
  product76,
  product77,
  product78,
  employee1,
  employee2,
  employee3,
  employee4,
  employee5,
  employee6,
  employee7,
  employee8,
  employee9,
} from "../assets/images";

import {
  service1,
  service2,
  service3,
  service4,
  service5,
  service6,
  service7,
  service8,
  sponsor1,
  sponsor2,
  sponsor3,
  sponsor4,
  sponsor5,
  sponsor6,
} from "../assets/icons";

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/products", label: "Shop" },
  { href: "/signup", label: "Sign Up" },
];

export const mobileLinks = [
  { href: "/", label: "Home" },
  { href: "/products", label: "Shop" },
  { href: "/about", label: "About" },
  { href: "/wishlist", label: "Wishlist" },
  { href: "/cart", label: "Cart" },
  { href: "/signup", label: "Sign Up" },
];

export const services = [
  {
    icon: service1,
    title: "free shipping",
    value: "Free delivery for all orders over $1000",
  },
  {
    icon: service2,
    title: "Order Tracking",
    value:
      "Enable easy track orders from the moment they are shipped until they are delivered.",
  },
  {
    icon: service3,
    title: "International Shipping",
    value: "We offer international shipping",
  },
  {
    icon: service4,
    title: "Product Demos",
    value: "Create video demos to showcase your products in action",
  },
  {
    icon: service5,
    title: "FAST DELIVERY",
    value:
      " Our fast delivery service ensures that your order reaches you in the shortest time possible",
  },

  {
    icon: service6,
    title: "24/7 CUSTOMER SERVICE",
    value: "Friendly 24/7 customer support",
  },
  {
    icon: service7,
    title: "MONEY BACK GUARANTEE",
    value: "We reurn money within 30 days",
  },
  {
    icon: service8,
    title: "flexible payment",
    value: "Pay with multiple credit cards",
  },
];

export const products = [
  {
    id: 1,
    img: product1,
    name: "iPhone 8",
    price: "250",
    reviews: "128",
    category: "phones",
    stars: 4,
  },
  {
    id: 2,
    img: product2,
    name: "iPhone 8 126GB",
    price: "200",
    reviews: "180",
    category: "phones",
    stars: 3.5,
  },
  {
    id: 3,
    img: product3,
    name: "iPhone 11 256GB",
    price: "420",
    reviews: "433",
    category: "phones",
    stars: 4.3,
  },
  {
    id: 4,
    img: product4,
    name: "iPhone 12 Pro",
    price: "542",
    reviews: "542",
    category: "phones",
    stars: 4.6,
    sale: 20,
  },
  {
    id: 5,
    img: product5,
    name: "iPhone 15 Pro",
    price: "1130",
    reviews: "871",
    category: "phones",
    stars: 4.9,
  },
  {
    id: 6,
    img: product6,
    name: "iPhone 15",
    price: "999",
    reviews: "754",
    category: "phones",
    stars: 4.8,
  },
  {
    id: 7,
    img: product7,
    name: "MacBook Pro",
    price: "590",
    reviews: "329",
    category: "laptops",
    stars: 4,
    best: true,
  },
  {
    id: 8,
    img: product8,
    name: "HP Laptop 15-dw",
    price: "316",
    reviews: "178",
    category: "laptops",
    stars: 4.3,
  },
  {
    id: 9,
    img: product9,
    name: "Mac Book 3",
    price: "440",
    reviews: "89",
    category: "laptops",
    stars: 4.5,
  },
  {
    id: 10,
    img: product10,
    name: "Razer Blade 15",
    price: "1650",
    reviews: "142",
    category: "laptops",
    stars: 4.6,
  },
  {
    id: 11,
    img: product11,
    name: "Razer Blade17",
    price: "1999",
    reviews: "215",
    category: "laptops",
    stars: 4.9,
    sale: 15,
  },
  {
    id: 12,
    img: product12,
    name: "ASUS X415",
    price: "490",
    reviews: "102",
    category: "laptops",
    stars: 4,
  },

  {
    id: 13,
    img: product13,
    name: "Logitech StreamCam",
    price: "168",
    reviews: "58",
    category: "webcams",
    stars: 4.6,
    sale: 40,
  },
  {
    id: 14,
    img: product14,
    name: "Logitech C505",
    price: "64",
    reviews: "168",
    category: "webcams",
    stars: 4.8,
  },
  {
    id: 15,
    img: product15,
    name: "Razer Kiyo",
    price: "81",
    startsFull: "4",
    reviews: "325",
    category: "webcams",
    stars: 4,
    best: true,
  },
  {
    id: 16,
    img: product16,
    name: "Logitech C920e",
    price: "359",
    reviews: "214",
    category: "webcams",
    stars: 4,
  },
  {
    id: 17,
    img: product17,
    name: "GoPro Hero 9",
    price: "197",
    reviews: "82",
    category: "gopro",
    stars: 3.5,
  },
  {
    id: 18,
    img: product18,
    name: "GoPro Hero 10",
    price: "215",
    reviews: "115",
    category: "gopro",
    stars: 4,
  },

  {
    id: 19,
    img: product19,
    name: "HyperX Cloud || ",
    price: "110",
    reviews: "340",
    category: "headphones",
    stars: 4.8,
    sale: 30,
  },
  {
    id: 20,
    img: product20,
    name: "Cloud Flight ",
    price: "159",
    reviews: "128",
    category: "headphones",
    stars: 4.8,
  },
  {
    id: 21,
    img: product21,
    name: "Razer Kraken V3 Pro",
    price: "194",
    reviews: "98",
    category: "headphones",
    stars: 3.8,
  },
  {
    id: 22,
    img: product22,
    name: "Razer Kraken Ultimate",
    price: "135",
    reviews: "198",
    category: "headphones",
    stars: 4.1,
  },
  {
    id: 23,
    img: product23,
    name: "PlayStation 5 Pulse",
    price: "93",
    reviews: "240",
    category: "headphones",
    stars: 4.3,
    best: true,
  },

  {
    id: 24,
    img: product24,
    name: "AirPods Max",
    price: "130",
    reviews: "320",
    category: "headphones",
    stars: 4.6,
  },
  {
    id: 25,
    img: product25,
    name: "PlayStation 5",
    price: "399",
    reviews: "846",
    category: "consoles",
    stars: 4.8,
    best: true,
  },
  {
    id: 26,
    img: product26,
    name: "Xbox series x",
    price: "459",
    reviews: "186",
    category: "consoles",
    stars: 4.7,
  },
  {
    id: 27,
    img: product27,
    name: "Wii",
    price: "149",
    reviews: "87",
    category: "consoles",
    stars: 4.3,
  },
  {
    id: 28,
    img: product28,
    name: "PlayStation 4",
    price: "126",
    reviews: "76",
    category: "consoles",
    stars: 3.8,
  },
  {
    id: 29,
    img: product29,
    name: "Xbox One",
    price: "259",
    reviews: "178",
    category: "consoles",
    stars: 4.4,
  },
  {
    id: 30,
    img: product30,
    name: "PlayStation 4 Slim",
    price: "212",
    reviews: "92",
    category: "consoles",
    stars: 4.2,
    sale: 50,
    best: true,
  },
  {
    id: 31,
    img: product31,
    name: "Nvidia 1050 TI 2GB Core i7 16GB RAM",
    price: "3800",
    reviews: "412",
    category: "computers",
    stars: 4.1,
    sale: 35,
  },
  {
    id: 32,
    img: product32,
    name: "Nvidia 1060 TI 4GB Core i7 16GB RAM",
    price: "3999",
    reviews: "358",
    category: "computers",
    stars: 4.3,
  },
  {
    id: 33,
    img: product33,
    name: "Nvidia 1050 TI 4GB Core i9 16GB RAM",
    price: "4400",
    reviews: "169",
    category: "computers",
    stars: 4.7,
  },
  {
    id: 34,
    img: product34,
    name: "Nvidia 1080 4GB Core i9 16GB RAM",
    price: "4950",
    reviews: "139",
    category: "computers",
    stars: 4.8,
  },
  {
    id: 35,
    img: product35,
    name: "Nvidia RTX 3060 Core i9 16GB RAM",
    price: "8410",
    reviews: "41",
    category: "computers",
    stars: 5,
    best: true,
  },
  {
    id: 36,
    img: product36,
    name: "Nvidia RTX 3080 Core i9 32GB RAM",
    price: "9100",
    reviews: "67",
    category: "computers",
    stars: 5,
  },

  {
    id: 37,
    img: product37,
    name: "ASUS 144HZ Monitor",
    price: "180",
    reviews: "124",
    category: "monitors",
    stars: 4.3,
    best: true,
  },
  {
    id: 38,
    img: product38,
    name: "IPS LCD Gaming Monitor",
    price: "110",
    reviews: "88",
    category: "monitors",
    stars: 4.2,
    sale: 60,
  },
  {
    id: 39,
    img: product39,
    name: "J6300 6Series Curved",
    price: "130",
    reviews: "241",
    category: "monitors",
    stars: 4.3,
  },
  {
    id: 40,
    img: product40,
    name: "ASUS monitor",
    price: "210",
    reviews: "123",
    category: "monitors",
    stars: 4.6,
  },
  {
    id: 41,
    img: product41,
    name: "KOORIU 26E3A",
    price: "60",
    reviews: "41",
    category: "monitors",
    stars: 4.5,
  },
  {
    id: 42,
    img: product42,
    name: "MSI Monitor 144HZ",
    price: "199",
    reviews: "514",
    category: "monitors",
    stars: 4.9,
  },
  {
    id: 43,
    img: product43,
    name: "Razer Huntsman Mini",
    price: "79",
    reviews: "89",
    category: "keyboards",
    stars: 4.3,
    sale: 30,
  },
  {
    id: 44,
    img: product44,
    name: "Razer BlackWidow V4 ||",
    price: "289",
    reviews: "112",
    category: "keyboards",
    stars: 4.8,
    best: true,
  },
  {
    id: 45,
    img: product45,
    name: "ASUS BlackWidow",
    price: "129",
    reviews: "259",
    category: "keyboards",
    stars: 4.7,
  },
  {
    id: 46,
    img: product46,
    name: "Razer BlackWidow V4",
    price: "299",
    reviews: "354",
    category: "keyboards",
    stars: 4.8,
  },
  {
    id: 47,
    img: product47,
    name: "Razer BlackWidow mini",
    price: "139",
    reviews: "74",
    category: "keyboards",
    stars: 4.4,
  },
  {
    id: 48,
    img: product48,
    name: "Logitech G Pro X",
    price: "249",
    reviews: "236",
    category: "keyboards",
    stars: 4.7,
  },
  {
    id: 49,
    img: product49,
    name: "Razer Pro",
    price: "99",
    reviews: "129",
    category: "mouses",
    stars: 4.7,
    sale: 25,
  },
  {
    id: 50,
    img: product50,
    name: "G502 Lightspeed ",
    price: "87",
    reviews: "219",
    category: "mouses",
    stars: 4.8,
  },
  {
    id: 51,
    img: product51,
    name: "Wireless Gaming Mouse",
    price: "69",
    reviews: "87",
    category: "mouses",
    stars: 4.8,
    best: true,
  },
  {
    id: 52,
    img: product52,
    name: "Razer Firely V2",
    price: "86",
    reviews: "149",
    category: "mouses",
    stars: 4.6,
  },
  {
    id: 53,
    img: product53,
    name: "Logitech Pro",
    price: "130",
    reviews: "158",
    category: "mouses",
    stars: 4.5,
  },
  {
    id: 54,
    img: product54,
    name: "Razer Basilisk V3",
    price: "189",
    reviews: "45",
    category: "mouses",
    stars: 4.5,
  },
  {
    id: 55,
    img: product55,
    name: "Logitech GX Yeti",
    price: "165",
    reviews: "255",
    category: "microphones",
    stars: 4.4,
    best: true,
  },
  {
    id: 56,
    img: product56,
    name: "Razer Seiren V3",
    price: "129",
    reviews: "187",
    category: "microphones",
    stars: 4.5,
  },
  {
    id: 57,
    img: product57,
    name: "HyperX Quadcast S RGV",
    price: "190",
    reviews: "410",
    category: "microphones",
    stars: 4.6,
  },
  {
    id: 58,
    img: product58,
    name: "Razer Seiren V2",
    price: "99",
    reviews: "68",
    category: "microphones",
    stars: 4.8,
  },
  {
    id: 59,
    img: product59,
    name: "Logitech G Yeti",
    price: "150",
    reviews: "310",
    category: "microphones",
    stars: 4.3,
  },
  {
    id: 60,
    img: product60,
    name: "Razer Seiren Mini",
    price: "37",
    reviews: "112",
    category: "microphones",
    stars: 3.8,
  },
  {
    id: 61,
    img: product61,
    name: "Apple Smartwatch",
    price: "86",
    reviews: "254",
    category: "smartwatches",
    stars: 4.3,
    sale: 40,
  },
  {
    id: 62,
    img: product62,
    name: "Apple Watch Ultra",
    price: "99",
    reviews: "532",
    category: "smartwatches",
    stars: 4.8,
  },
  {
    id: 63,
    img: product63,
    name: "Apple BlogtoWatch",
    price: "34",
    reviews: "54",
    category: "smartwatches",
    stars: 4.7,
    best: true,
  },
  {
    id: 64,
    img: product64,
    name: "Xiaomi Mi Smart ",
    price: "54",
    reviews: "364",
    category: "smartwatches",
    stars: 4.2,
  },
  {
    id: 65,
    img: product65,
    name: "Samsung Jordan",
    price: "120",
    reviews: "241",
    category: "smartwatches",
    stars: 4.7,
  },
  {
    id: 66,
    img: product66,
    name: "Black Square",
    price: "41",
    reviews: "12",
    category: "smartwatches",
    stars: 4.5,
  },
  {
    id: 67,
    img: product67,
    name: "Nintendo switch",
    price: "310",
    reviews: "810",
    category: "handheldgame",
    stars: 4.9,
  },
  {
    id: 68,
    img: product68,
    name: "Stean Deck",
    price: "320",
    reviews: "514",
    category: "handheldgame",
    stars: 4.8,
  },
  {
    id: 69,
    img: product69,
    name: "Sony Portal",
    price: "199",
    reviews: "475",
    category: "handheldgame",
    stars: 4.7,
  },
  {
    id: 70,
    img: product70,
    name: "Apple iPad Pro 13",
    price: "1341",
    reviews: "872",
    category: "ipads",
    stars: 4.8,
  },
  {
    id: 71,
    img: product71,
    name: "Apple iPad Pro 11",
    price: "1108",
    reviews: "657",
    category: "ipads",
    stars: 4.7,
  },
  {
    id: 72,
    img: product72,
    name: "Apple iPad Air 2",
    price: "134",
    reviews: "112",
    category: "ipads",
    stars: 4,
  },
  {
    id: 73,
    img: product73,
    name: "Apple iPad 10th",
    price: "120",
    reviews: "69",
    category: "ipads",
    stars: 3.8,
  },
  {
    id: 74,
    img: product74,
    name: "Meta VR",
    price: "3541",
    reviews: "1238",
    category: "virtualreality",
    stars: 4.9,
  },
  {
    id: 75,
    img: product75,
    name: "VR Headset",
    price: "351",
    reviews: "325",
    category: "virtualreality",
    stars: 4.5,
    best: true,
  },
  {
    id: 76,
    img: product76,
    name: "Oculus Quest Headset",
    price: "243",
    reviews: "187",
    category: "virtualreality",
    stars: 4.6,
  },
  {
    id: 77,
    img: product77,
    name: "Go Pro Hero 11",
    price: "291",
    reviews: "346",
    category: "gopro",
    stars: 4.6,
  },
  {
    id: 78,
    img: product78,
    name: "Go Pro Hero 12",
    price: "345",
    reviews: "541",
    category: "gopro",
    stars: 4.9,
  },
];

export const stats = [
  {
    label: "Monthly Products sale",
    value: "+20.5 K",
  },
  {
    label: "Sallers active our site",
    value: "+10 K",
  },
  {
    label: "Customers active in our site",
    value: "+8 K",
  },
  {
    label: "5-star reviews",
    value: "+4.8 K",
  },
  {
    label: "Products sold",
    value: "+1 M",
  },
  {
    label: "customer satisfaction reviews",
    value: "98 %",
  },
  {
    label: "countries shipped to",
    value: "120",
  },
  {
    label: " website visits per month",
    value: "+220 K",
  },
];

export const discountsArr = [
  { id: 1, percent: 60 },
  { id: 2, percent: 50 },
  { id: 3, percent: 40 },
  { id: 4, percent: 30 },
  { id: 5, percent: 10 },
  { id: 6, percent: 20 },
];

export const team = [
  {
    name: "Mark Johnson",
    img: employee1,
    position: "CEO",
  },
  {
    name: "Andrew Johnson",
    img: employee2,
    position: "Co-Founder",
  },
  {
    name: "Matthew Davis",
    img: employee3,
    position: "Chief Technology Officer",
  },
  {
    name: "Ryan Martinez",
    img: employee4,
    position: "Chief Operating Officer",
  },
  {
    name: "Emma Watson",
    img: employee8,
    position: "Managing Director",
  },
  {
    name: "Christopher Lee",
    img: employee5,
    position: "Chief Financial Officer",
  },

  {
    name: "Yahya El Khayat",
    img: employee7,
    position: "Head of Product Development",
  },
  {
    name: "Anas Ajaaanan",
    img: employee6,
    position: "Head of Marketing",
  },
  {
    name: "Mousaab Arektout ",
    img: employee9,
    position: "Chief Sales",
  },
];

export const sponsors = [
  { icon: sponsor1, id: 1 },
  { icon: sponsor2, id: 2 },
  { icon: sponsor3, id: 3 },
  { icon: sponsor4, id: 4 },
  { icon: sponsor5, id: 5 },
  { icon: sponsor6, id: 6 },
];

export const footerLinks = [
  {
    label: "Account",
    links: [
      { href: "/", value: "My Account" },
      { href: "/", value: "Login / Register" },
      { href: "/", value: "Cart" },
      { href: "/", value: "Wishlist" },
      { href: "/", value: "Shop" },
    ],
  },
  {
    label: "Company",
    links: [
      {
        href: "/",
        value: "About",
      },
      { href: "/", value: "Partners" },
      { href: "/", value: "Customers" },
      { href: "/", value: "Careers" },
      { href: "/", value: "Contact us" },
    ],
  },
  {
    label: "Help & FAQs",
    links: [
      {
        href: "/",
        value: "Online Ordering",
      },
      { href: "/", value: "Shipping" },
      { href: "/", value: "Billing" },
      { href: "/", value: "Returns" },
      { href: "/", value: "Services" },
    ],
  },
  {
    label: "Quick Link",
    links: [
      { href: "/", value: "Privacy Policy" },
      { href: "/", value: "Terms Of Use" },
      { href: "/", value: "Coockies" },
      { href: "/", value: "FAQ" },
      { href: "/", value: "Contact" },
    ],
  },
];
